Core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(),name='home'),
    path('blog/',include('blog.urls',namespace='blog'))
]

blog/urls.py
from django.urls import path
from .views import  BlogListView,BlogCreate,DeleteBlog,BlogDetailView,BlogUpdate

app_name = 'blog'

urlpatterns = [
    path('Inicio/',BlogListView.as_view(),name='home'),
    path('blog_create/',BlogCreate.as_view(),name='blog_create'),
    path('<int:pk>/',BlogDetailView.as_view(),name='blog_detail'),
    path('update/<int:pk>/',BlogUpdate.as_view(),name='update'),
     path('delete/<int:pk>/',DeleteBlog.as_view(),name='delete')
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self) -> str:
        return self.title

blog/forms.py
from django import forms
from.models import Post


class PostCreateForms(forms.ModelForm):
    class Meta:
        model = Post
        fields =  ['title','content']

Core/views.py
from django.views.generic import View
from django.shortcuts import render,redirect

class HomeView(View):
    def get(self,request,*args,**kwargs):
        context  ={

        }
        return render(request,'home.html',context)

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import View,UpdateView,DeleteView
from .forms import PostCreateForms
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self,request,*args,**kwargs):
        post = Post.objects.all()
        context = {
            'posts':post
        }
        return render(request,'blog_list.html',context)
    

class BlogCreate(View):

    def get(self,request,*args,**kwargs):
        forms = PostCreateForms()

        context = {
            'forms':forms
        }
        return render(request,'blog_create.html',context)
    

    def post(self,request,*args,**kwargs):
        if request.method == 'POST':
            forms = PostCreateForms(request.POST)
            if forms.is_valid():
                forms.save()
                return redirect('blog:home') 
        else:
            forms = PostCreateForms()

        context = {
            
        }
        return render(request,'blog_create.html',context)


class BlogDetailView(View):
    def get(self,request,pk,*args,**kwargs):
        post = get_object_or_404(Post,pk=pk)

        context = {
            'post':post
        }
        return render(request,'blog_detail.html',context)
    

class BlogUpdate(UpdateView):
       model=Post
       fields=['title','content']
       template_name='blog_update.html'


       def get_success_url(self):
           pk = self.kwargs['pk']
           return reverse_lazy('blog:blog_detail',kwargs={'pk':pk})
       

class DeleteBlog(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>

 <div class="container">
{% block  content %}
        
{% endblock  %}

 </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>
    
    

templates/blog_create.html
<form action="" method="post">
    {% csrf_token %}
    {{forms.as_p}}
    <button type="submit">Crear Post</button>
</form>

templates/blog_delete.html
{% extends 'base.html' %}

{% block content %}
    
<div class="card w-75 mb-3" style="margin-top: 39px;">
    <div class="card-body">
    <form method="post">{% csrf_token %} 
        <p class="card-text">Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
      <button class="btn btn-primary">Confirm</button>
    </form>
    </div>
  </div>
  
{% endblock %}

templates/blog_detail.html
<h4>{{post.title}}</h4>

<textarea name="" id="" cols="30" rows="10">{{post.content}}</textarea>

templates/blog_list.html
{% extends 'base.html' %}


{% block content %}
    <!-- <h1 class="mt-5 mb-7">bienvenido al blog</h1>

<a class=" text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" href="{% url 'blog:blog_create' %}">create Blog</a>

{% for post in posts %}
    <a href="{% url 'blog:blog_detail' post.id %}">{{post.title}}</a>
     <a href="{% url 'blog:update' post.id %}">update</a>
     <a href="{% url 'blog:delete' post.id %}">delete</a>
{% endfor %} -->

<header>
    <!-- Intro settings -->
    <style>
      #intro {
        /* Margin to fix overlapping fixed navbar */
        margin-top: 58px;
      }
      @media (max-width: 991px) {
        #intro {
          /* Margin to fix overlapping fixed navbar */
          margin-top: 45px;
        }
      }
    </style>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand"  href="{% url 'blog:home'  %}">
          <h3 style="margin-top: -3px;" height="16" alt="" loading="lazy">RhanBlog👨‍💻</h3>
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
          <h1></h1>
        </button>
        <div class="collapse navbar-collapse " id="navbarExample01">
          <ul class="navbar-nav me-auto  mb-2 mb-lg-0" style="margin-left: 970px;">
            <li class="nav-item active">
                <a  type="button" href="{% url 'blog:blog_create' %}" class="btn btn-primary">Create Post</a>
            </li>
            
          </ul>

          <ul class="navbar-nav d-flex flex-row">
            <!-- Icons -->
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow"
                target="_blank">
                <i class="fab fa-youtube"></i>
              </a>
            </li>
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="https://www.facebook.com/mdbootstrap" rel="nofollow" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="https://twitter.com/MDBootstrap" rel="nofollow" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="https://github.com/mdbootstrap/mdb-ui-kit" rel="nofollow" target="_blank">
                <i class="fab fa-github"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->

    <!-- Jumbotron -->
    <div id="intro" class="p-5 text-center " style="background-color: rgb(16, 154, 247);">
      <h1 class="mb-3 h2">RhanBlog👨‍💻</h1>
     
    </div>
    <!-- Jumbotron -->
  </header>
  <!--Main Navigation-->

  <!--Main layout-->
  <main class="my-5">
    <div class="container">
      <!--Section: Content-->
      <section class="text-center">
        <h4 class="mb-5"><strong>Latest posts</strong></h4>

        <div class="row">
            {% for post in posts %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img src="https://mdbootstrap.com/img/new/standard/nature/023.jpg" class="img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">
                  {{post.content}}
                </p>
                <a href="#!" class="btn btn-primary">Read</a>
                <a href="{% url 'blog:update' post.id %}" class="btn btn-info" >update</a>
                <a href="{% url 'blog:delete' post.id %}" class="btn btn-danger">delete</a>
              </div>
            </div>
          </div>
        {% endfor %}
          
          </div>
        </div>
      </section>
      <!--Section: Content-->

      <!-- Pagination -->
     
    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="bg-light text-lg-start">
    

    <hr class="m-0" />

    

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgb(14, 186, 238);">
      © 2023 Copyright:
      <a class="text-dark">Rhanzess</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!--Footer-->


{% endblock %}

templates/blog_update.html
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">guardar</button>
</form>

templates/home.html
{% extends 'base.html' %}

{% block  content  %}

<div style="margin-top:40px;">
    <h1>Hi Developer</h1>


    <a class="btn btn-warning" href="{% url 'blog:home' %}">Enter the blog</a>
</div>
    
    
{% endblock   %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>